name: Github Actions Build and Deploy Demo
on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-east-1
  MY_BLOG_BUCKET_NAME: my-blog-ui

jobs:
  build-and-deploy:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install

      - name: Run UTs
        run: npm test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: MyBlogStack
          template: ./cloudformation/stack.yml
          parameter-overrides: "BucketName=${{ env.MY_BLOG_BUCKET_NAME }}"

      - name: Build production app
        run: npm run build

      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://${{ env.MY_BLOG_BUCKET_NAME }} --delete --acl public-read
